services:
  # 1. Base de Dados
  db:
    image: postgres:15-alpine
    container_name: fithub-db
    restart: always
    environment:
      POSTGRES_DB: fithub
      POSTGRES_USER: fithubuser
      POSTGRES_PASSWORD: fithubpassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # 2. Backend (API)
  backend:
    # O Docker vai buscar os arquivos exatamente nesta pasta do seu PC:
    build: "C:/Users/Cauã/OneDrive/Desktop/PRG04/prg04backend/fithub-api"
    container_name: fithub-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fithub
      SPRING_DATASOURCE_USERNAME: fithubuser
      SPRING_DATASOURCE_PASSWORD: fithubpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./uploads_data:/app/uploads

  # 3. Frontend (Web)
  frontend:
    build: . # Usa a pasta onde este arquivo está (fithub-web)
    container_name: fithub-web
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
